name: hello-world-perm
description: first declaratively created permission set
resources:
  - resource: Integration
    access: READ_ACCESS
  - resource: Administration
    access: READ_ACCESS
  - resource: Access
    access: READ_ACCESS
---
name: hello-world-provider
minimumRole: hello-world-role # Referencing the declarative minimum access role.
uiEndpoint: central-stackrox.apps.dh-05-31-overconfident-price.openshift.infra.rox.systems
groups:
- key: "email"
  value: "daniel@haus.de"
  role: "Admin"
oidc:
  issuer: dhaus.eu.auth0.com
  mode: fragment
  clientID: JEH7b9q3zVScD3Pirmh173tB70NYCUcg
---
name: hello-world-role
description: first declaratively created role
accessScope: Unrestricted
permissionSet: hello-world-perm
