name: hello-world
description: first declaratively created permission set
resources:
  - resource: Integration
    access: READ_ACCESS
  - resource: Administration
    access: READ_ACCESS
  - resource: Access
    access: READ_ACCESS
---
name: hello-world
description: first declaratively created role
permissionSet: hello-world # Referencing the previously created permission set.
accessScope: UnrestrictedError # Referencing a system resource, the "Unrestricted" access scope.
---
